#ifndef DOT3ADAGGPORTLISTTABLE_OIDS_H
#define DOT3ADAGGPORTLISTTABLE_OIDS_H
#include <sys/types.h>

#define DOT3ADAGGPORTLISTTABLE_OID 1, 2, 840, 802, 10006, 300, 43, 1, 1, 2
#define COLUMN_DOT3ADAGGPORTLISTPORTS 1

#define DOT3ADAGGPORTLISTTABLE_MIN_COL COLUMN_DOT3ADAGGPORTLISTPORTS
#define DOT3ADAGGPORTLISTTABLE_MAX_COL COLUMN_DOT3ADAGGPORTLISTPORTS
#endif