#ifndef DOT3ADAGGTABLE_OIDS_H
#define DOT3ADAGGTABLE_OIDS_H
#include <sys/types.h>

#define DOT3ADAGGTABLE_OID 1, 2, 840, 802, 10006, 300, 43, 1, 1, 1
#define COLUMN_DOT3ADAGGINDEX 1
#define COLUMN_DOT3ADAGGMACADDRESS 2
#define COLUMN_DOT3ADAGGACTORSYSTEMPRIORITY 3
#define COLUMN_DOT3ADAGGACTORSYSTEMID 4
#define COLUMN_DOT3ADAGGAGGREGATEORINDIVIDUAL 5
#define COLUMN_DOT3ADAGGACTORADMINKEY 6
#define COLUMN_DOT3ADAGGACTOROPERKEY 7
#define COLUMN_DOT3ADAGGPARTNERSYSTEMID 8
#define COLUMN_DOT3ADAGGPARTNERSYSTEMPRIORITY 9
#define COLUMN_DOT3ADAGGPARTNEROPERKEY 10
#define COLUMN_DOT3ADAGGCOLLECTORMAXDELAY 11

#define DOT3ADAGGTABLE_MIN_COL COLUMN_DOT3ADAGGINDEX
#define DOT3ADAGGTABLE_MAX_COL COLUMN_DOT3ADAGGCOLLECTORMAXDELAY
#endif