#ifndef DOT3ADAGGPORTSTATSTABLE_OIDS_H
#define DOT3ADAGGPORTSTATSTABLE_OIDS_H
#include <sys/types.h>

#define DOT3ADAGGPORTSTATSTABLE_OID 1, 2, 840, 802, 10006, 300, 43, 1, 2, 2
#define COLUMN_DOT3ADAGGPORTSTATSLACPDUSRX 1
#define COLUMN_DOT3ADAGGPORTSTATSMARKERPDUSRX 2
#define COLUMN_DOT3ADAGGPORTSTATSMARKERRESPONSEPDUSRX 3
#define COLUMN_DOT3ADAGGPORTSTATSUNKNOWNRX 4
#define COLUMN_DOT3ADAGGPORTSTATSILLEGALRX 5
#define COLUMN_DOT3ADAGGPORTSTATSLACPDUSTX 6
#define COLUMN_DOT3ADAGGPORTSTATSMARKERPDUSTX 7
#define COLUMN_DOT3ADAGGPORTSTATSMARKERRESPONSEPDUSTX 8

#define DOT3ADAGGPORTSTATSTABLE_MIN_COL COLUMN_DOT3ADAGGPORTSTATSLACPDUSRX
#define DOT3ADAGGPORTSTATSTABLE_MAX_COL                                        \
    COLUMN_DOT3ADAGGPORTSTATSMARKERRESPONSEPDUSTX
#endif